### ISSUE TITLE
Change the primary colour of material kit css

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#309] opened 2022-01-08 05:54 UTC
**Is your feature request related to a problem? Please describe.**
The primary colour of material kit is purple. But we don't need to use purple as our primary colour. (ex: on links, tabs, buttons, etc)

**Describe the solution you'd like**
The primary colour should be the colour of `text-info`. See the [components](https://demos.creative-tim.com/material-kit-bs4/index?_ga=2.158042362.1967954257.1641402362-149862726.1641402362) page. Please recompile the `material-kit.css` and relevant files to change the colour.  Use scss to recompile.

Please follow the following documentation:
https://demos.creative-tim.com/material-kit/docs/2.1/getting-started/build-tools.html

**Are you working on it?**
No

**Comment by jayasanka-sack** [comment] 2022-01-08 06:02
@AniketSharma24 can you help us to fix this?

**Comment by Yoshitha-SACK** [comment] 2022-01-09 00:50
Shall I work on this?

**Comment by AniketSharma24** [comment] 2022-01-09 12:03
@Yoshitha-SACK, @jayasanka-sack  I have done the research and was not able to find the solution. I am backing out. Please go ahead and apply the fixes if you have any.

**Comment by Piumal1999** [comment] 2022-01-10 18:20
Reopening because the issue is not fixed by the merged pr.

**Comment by Piumal1999** [comment] 2022-01-12 11:26
@jayasanka-sack which colour do we use as the primary colour? `#008CC4` (color of "our history" button) or `#00A6C4` (color of other buttons)? Btw, the colour used in the contact page is `#2E8DF3`

**Comment by VishwaAmarasinghe** [comment] 2022-01-12 11:59
@Yoshitha-SACK are you doing this or shall I

**Comment by jayasanka-sack** [comment] 2022-01-14 05:21
@Piumal1999 yes it would be better. But it introduces a lot of work to introduce a new colour (with shades). Changing it to an existing colour is a bit easy.

**Closed** 2022-01-14 10:02 UTC
Labels: enhancement, help wanted
